Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met TypeError: list indices must be integers or slices, not tuple
Error processing book/Scan_20250618 (8)_1L.tif [R]: dewarp faalde met TypeError: list indices must be integers or slices, not tuple
Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met TypeError: list indices must be integers or slices, not tuple
Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met TypeError: list indices must be integers or slices, not tuple
Error processing book/Scan_20250618 (8)_1L.tif [R]: dewarp faalde met TypeError: list indices must be integers or slices, not tuple
Verwerk bestand Scan_20250618 (8)_1L
> Page 85
![Scan_20250618 (8)_1L_L_dewarped.tif](test_output/Scan_20250618 (8)_1L_L_dewarped.tif)

Verwerk bestand Scan_20250618 (8)_1L
> Page 85
![Scan_20250618 (8)_1L_L_dewarped.tif](test_output/Scan_20250618 (8)_1L_L_dewarped.tif)

Verwerk bestand Scan_20250618 (8)_1L
> Page 85
![Scan_20250618 (8)_1L_L_dewarped.tif](test_output/Scan_20250618 (8)_1L_L_dewarped.tif)

Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met NameError: name 'result' is not defined
Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met NameError: name 'loss_0' is not defined
Verwerk bestand Scan_20250618 (8)_1L
> Page 
![Scan_20250618 (8)_1L_L_dewarped.tif](test_output/Scan_20250618 (8)_1L_L_dewarped.tif)

Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met ValueError: need at least one array to concatenate
Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met ValueError: zero-size array to reduction operation minimum which has no identity
Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met OverflowError: cannot convert float infinity to integer
Verwerk bestand Scan_20250618 (8)_1L
> Page 
![Scan_20250618 (8)_1L_L_dewarped.tif](test_output/Scan_20250618 (8)_1L_L_dewarped.tif)

Verwerk bestand Scan_20250618 (8)_1L
> Page 
![Scan_20250618 (8)_1L_L_dewarped.tif](test_output/Scan_20250618 (8)_1L_L_dewarped.tif)

Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met error: OpenCV(4.10.0) /croot/opencv-suite_1744632477110/work/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<1>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

Verwerk bestand Scan_20250618 (8)_1L
> Page 6
![Scan_20250618 (8)_1L_L_dewarped.tif](test_output/Scan_20250618 (8)_1L_L_dewarped.tif)

Verwerk bestand Scan_20250618 (8)_1L
> Page 
![Scan_20250618 (8)_1L_L_textlines.tif](test_output/Scan_20250618 (8)_1L_L_textlines.tif)

![Scan_20250618 (8)_1L_L_dewarped.tif](test_output/Scan_20250618 (8)_1L_L_dewarped.tif)

Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met error: OpenCV(4.10.0) /croot/opencv-suite_1744632477110/work/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<1>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met error: OpenCV(4.10.0) /croot/opencv-suite_1744632477110/work/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<1>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

Verwerk bestand Scan_20250618 (8)_1L
> Page 
![Scan_20250618 (8)_1L_L_dewarped.tif](test_output/Scan_20250618 (8)_1L_L_dewarped.tif)

Verwerk bestand Scan_20250618 (8)_1L
> Page 
![Scan_20250618 (8)_1L_L_dewarped.tif](test_output/Scan_20250618 (8)_1L_L_dewarped.tif)

Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met error: OpenCV(4.10.0) /croot/opencv-suite_1744632477110/work/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<1>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met error: OpenCV(4.10.0) /croot/opencv-suite_1744632477110/work/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<1>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

Verwerk bestand Scan_20250618 (8)_1L
> Page 
![Scan_20250618 (8)_1L_L_dewarped.tif](test_output/Scan_20250618 (8)_1L_L_dewarped.tif)

Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met error: OpenCV(4.10.0) /croot/opencv-suite_1744632477110/work/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<1>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met error: OpenCV(4.10.0) /croot/opencv-suite_1744632477110/work/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<1>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met error: OpenCV(4.10.0) /croot/opencv-suite_1744632477110/work/modules/imgproc/src/connectedcomponents.cpp:5623: error: (-215:Assertion failed) L.channels() == 1 && I.channels() == 1 in function 'connectedComponents_sub1'

Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met error: OpenCV(4.10.0) /croot/opencv-suite_1744632477110/work/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<1>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met error: OpenCV(4.10.0) /croot/opencv-suite_1744632477110/work/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<1>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

Verwerk bestand Scan_20250618 (8)_1L
> Page 
![Scan_20250618 (8)_1L_L_dewarped.tif](test_output/Scan_20250618 (8)_1L_L_dewarped.tif)

Verwerk bestand Scan_20250618 (8)_1L
> Page 
![Scan_20250618 (8)_1L_L_dewarped.tif](test_output/Scan_20250618 (8)_1L_L_dewarped.tif)

Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met error: OpenCV(4.10.0) /croot/opencv-suite_1744632477110/work/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<1>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met error: OpenCV(4.10.0) /croot/opencv-suite_1744632477110/work/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<1>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

Verwerk bestand Scan_20250618 (8)_1L
> Page 
![Scan_20250618 (8)_1L_L_textlines.tif](test_output/Scan_20250618 (8)_1L_L_textlines.tif)

![Scan_20250618 (8)_1L_L_dewarped.tif](test_output/Scan_20250618 (8)_1L_L_dewarped.tif)

Verwerk bestand Scan_20250618 (8)_1L
> Page 85
![Scan_20250618 (8)_1L_L_dewarped.tif](test_output/Scan_20250618 (8)_1L_L_dewarped.tif)

Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met NameError: name 'Of' is not defined
Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met TypeError: go_dewarp() got an unexpected keyword argument 'f'
Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met NameError: name 'Of' is not defined
Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met error: OpenCV(4.10.0) /croot/opencv-suite_1744632477110/work/modules/imgproc/src/connectedcomponents.cpp:5623: error: (-215:Assertion failed) L.channels() == 1 && I.channels() == 1 in function 'connectedComponents_sub1'

Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met NameError: name 'points' is not defined
Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met ValueError: need at least one array to concatenate
Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met ValueError: need at least one array to concatenate
Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met ValueError: need at least one array to concatenate
Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met ValueError: need at least one array to concatenate
Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met ValueError: need at least one array to concatenate
Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met OverflowError: cannot convert float infinity to integer
Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met ValueError: need at least one array to concatenate
Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met ValueError: need at least one array to concatenate
Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met ValueError: need at least one array to concatenate
Verwerk bestand 2
Error processing booko/2.jpg: CUDA out of memory. Tried to allocate 26.00 MiB. GPU 0 has a total capacity of 1.93 GiB of which 24.81 MiB is free. Process 20200 has 428.00 MiB memory in use. Including non-PyTorch memory, this process has 402.00 MiB memory in use. Process 20202 has 428.00 MiB memory in use. Of the allocated memory 265.44 MiB is allocated by PyTorch, and 64.56 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Verwerk bestand 1
Error processing booko/1.jpg [L]: dewarp faalde met ValueError: need at least one array to concatenate
Error processing booko/1.jpg [R]: dewarp faalde met ValueError: need at least one array to concatenate
Verwerk bestand gedraaid
Error processing booko/gedraaid.png [L]: dewarp faalde met error: OpenCV(4.10.0) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - Can't parse 'pt2'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt2'. Sequence item with index 0 has a wrong type

Error processing booko/gedraaid.png [R]: dewarp faalde met ValueError: need at least one array to concatenate
Verwerk bestand gedraaid
Error processing booko/gedraaid.png: CUDA out of memory. Tried to allocate 32.00 MiB. GPU 0 has a total capacity of 1.93 GiB of which 18.94 MiB is free. Process 21816 has 402.00 MiB memory in use. Process 21817 has 402.00 MiB memory in use. Including non-PyTorch memory, this process has 354.00 MiB memory in use. Of the allocated memory 261.75 MiB is allocated by PyTorch, and 20.25 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Verwerk bestand 1
Error processing booko/1.jpg: CUDA out of memory. Tried to allocate 26.00 MiB. GPU 0 has a total capacity of 1.93 GiB of which 26.56 MiB is free. Including non-PyTorch memory, this process has 402.00 MiB memory in use. Process 21817 has 402.00 MiB memory in use. Process 21820 has 354.00 MiB memory in use. Of the allocated memory 265.44 MiB is allocated by PyTorch, and 64.56 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Verwerk bestand 2
Error processing booko/2.jpg: CUDA out of memory. Tried to allocate 26.00 MiB. GPU 0 has a total capacity of 1.93 GiB of which 26.56 MiB is free. Process 21816 has 402.00 MiB memory in use. Including non-PyTorch memory, this process has 402.00 MiB memory in use. Process 21820 has 354.00 MiB memory in use. Of the allocated memory 265.44 MiB is allocated by PyTorch, and 64.56 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Verwerk bestand gedraaid
Error processing booko/gedraaid.png: CUDA out of memory. Tried to allocate 32.00 MiB. GPU 0 has a total capacity of 1.93 GiB of which 26.56 MiB is free. Process 22030 has 402.00 MiB memory in use. Process 22029 has 402.00 MiB memory in use. Including non-PyTorch memory, this process has 354.00 MiB memory in use. Of the allocated memory 261.75 MiB is allocated by PyTorch, and 20.25 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Verwerk bestand 2
Error processing booko/2.jpg: CUDA out of memory. Tried to allocate 26.00 MiB. GPU 0 has a total capacity of 1.93 GiB of which 26.56 MiB is free. Including non-PyTorch memory, this process has 402.00 MiB memory in use. Process 22029 has 402.00 MiB memory in use. Process 22031 has 354.00 MiB memory in use. Of the allocated memory 265.44 MiB is allocated by PyTorch, and 64.56 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Verwerk bestand 1
Error processing booko/1.jpg: CUDA out of memory. Tried to allocate 26.00 MiB. GPU 0 has a total capacity of 1.93 GiB of which 26.56 MiB is free. Process 22030 has 402.00 MiB memory in use. Including non-PyTorch memory, this process has 402.00 MiB memory in use. Process 22031 has 354.00 MiB memory in use. Of the allocated memory 265.44 MiB is allocated by PyTorch, and 64.56 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Verwerk bestand gedraaid
Error processing booko/gedraaid.png: CUDA out of memory. Tried to allocate 14.00 MiB. GPU 0 has a total capacity of 1.93 GiB of which 22.88 MiB is free. Process 22898 has 402.00 MiB memory in use. Process 22897 has 402.00 MiB memory in use. Including non-PyTorch memory, this process has 386.00 MiB memory in use. Of the allocated memory 293.75 MiB is allocated by PyTorch, and 20.25 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Verwerk bestand 2
Error processing booko/2.jpg: CUDA out of memory. Tried to allocate 26.00 MiB. GPU 0 has a total capacity of 1.93 GiB of which 30.50 MiB is free. Including non-PyTorch memory, this process has 402.00 MiB memory in use. Process 22897 has 402.00 MiB memory in use. Process 22899 has 386.00 MiB memory in use. Of the allocated memory 265.44 MiB is allocated by PyTorch, and 64.56 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Verwerk bestand 1
Error processing booko/1.jpg: CUDA out of memory. Tried to allocate 26.00 MiB. GPU 0 has a total capacity of 1.93 GiB of which 30.50 MiB is free. Process 22898 has 402.00 MiB memory in use. Including non-PyTorch memory, this process has 402.00 MiB memory in use. Process 22899 has 386.00 MiB memory in use. Of the allocated memory 265.44 MiB is allocated by PyTorch, and 64.56 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met TypeError: go_dewarp() got an unexpected keyword argument 'flatbed'
Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met TypeError: go_dewarp() got an unexpected keyword argument 'flatbed'
Verwerk bestand Scan_20250618 (8)_1L
> Page 85
![Scan_20250618 (8)_1L_L_dewarped.tif](test_output/Scan_20250618 (8)_1L_L_dewarped.tif)

Verwerk bestand Scan_20250618 (8)_1L
Error processing book/Scan_20250618 (8)_1L.tif [L]: dewarp faalde met TypeError: kim2014() got an unexpected keyword argument 'flatbed'
Verwerk bestand Scan_20250618 (8)_1L
> Page 85
![Scan_20250618 (8)_1L_L_dewarped.tif](test_output/Scan_20250618 (8)_1L_L_dewarped.tif)

Verwerk bestand Scan_20250618 (8)_1L
> Page 85
![Scan_20250618 (8)_1L_L_dewarped.tif](test_output/Scan_20250618 (8)_1L_L_dewarped.tif)

Verwerk bestand Scan_20250618 (8)_1L
> Page 85
![Scan_20250618 (8)_1L_L_textlines.tif](test_output/Scan_20250618 (8)_1L_L_textlines.tif)

![Scan_20250618 (8)_1L_L_dewarped.tif](test_output/Scan_20250618 (8)_1L_L_dewarped.tif)

